### Get All Stories
GET http://localhost:{{API_PORT}}/api/v1/stories HTTP/1.1
Accept: application/json

### Get Single Story
GET http://localhost:{{API_PORT}}/api/v1/stories/1 HTTP/1.1
Accept: application/json

### Create a New Story
POST http://localhost:{{API_PORT}}/api/v1/stories HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "title": "New Story",
  "content": "This is the content of the new story."
}

### Update a Story
PUT http://localhost:{{API_PORT}}/api/v1/stories/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "title": "Updated Story",
  "content": "This is the updated content of the story."
}

### Delete a Story
DELETE http://localhost:{{API_PORT}}/api/v1/stories/1 HTTP/1.1
Accept: application/json
